In [1]:
import os
import tensorflow as tf
from PIL import Image

# cwd = os.getcwd()  #获取当前目录
# classes = {'bus','flower','long','horse','elephant'}  #预先定义自己要分的类别

# #制作tfrecord数据
# writer = tf.python_io.TFRecordWriter('fenlei_train.tfrecords')  #要生成的TFRecord的名字

# def _int64_feature(value):
#     return tf.train.Feature(int64_list = tf.train.Int64List(value=[value]))
# def _bytes_feature(value):
#     return tf.train.Feature(bytes_list= tf.train.BytesList(value=[value]))

# for index, name in enumerate(classes):  #第一个循环是打开马 和 花这两个文件夹
#     class_path = cwd+'/'+name+'/'
    
#     for img_name in os.listdir(class_path):  #开始遍历每一张图片
#         img_path = class_path+img_name  #每个图片的地址
        
#         img = Image.open(img_path)  #打开每一张图片
#         img = img.resize((64,64))  #将图片设置为指定的大小
#         img_raw = img.tobytes() #将图片转化为二进制格式
        
#           ######### 这里的内容就是对label image进行封装
#         example = tf.train.Example(
#             features=tf.train.Features(feature={
#                 'label':_int64_feature(index),
#                 'img_raw':_bytes_feature(img_raw)
#                 }))
#           #########
            
#         writer.write(example.SerializeToString())#序列化为字符串
# writer.close()

            
    
    
    


#定义读取TFRecord的数据函数
def read_and_decode(filename):
    filename_queue = tf.train.string_input_producer([filename])  #生成一个queue队列
    reader = tf.TFRecordReader()
    _,serialized_example = reader.read(filename_queue) #返回文件名和文件

        #解析label和image信息，这个名字需要与生成TFRecord的时候一致
    features = tf.parse_single_example(serialized_example,
                                       features={
                                           'label':tf.FixedLenFeature([],tf.int64),
                                           'img_raw':tf.FixedLenFeature([],tf.string)
                                            }) #将image数据个label取出来
    img = tf.decode_raw(features['img_raw'],tf.uint8)
    img = tf.reshape(img,[64,64,3]) #reshape为64*64的3通道照片
    label = tf.cast(features['label'],tf.int32) #tf.cast就是进行数据转换为int32，在数据流中抛出label张量
    return img,label

############其实就是到这里就可以把数据导入到神经网络中去， xs,ys = read_and_decode(filename)



#保存以及显示图片
#gen_pic = '/home/ginchoeng/jupyternotebook/yunxing/gen_pic'#获取当前的运行路径 ,这里就是把生成标签的图片保存的路径
init = tf.global_variables_initializer()
batch = read_and_decode('fenlei_train.tfrecords')

with tf.Session() as sess:
    sess.run(init)
    coord = tf.train.Coordinator()
    threads =tf.train.start_queue_runners(coord=coord)

    for i in range(400):
        example, lab = sess.run(batch)
#         img = Image.fromarray(example,'RGB')
#         img.save(gen_pic+'/'+str(i)+'_label_'+str(lab)+'.jpg')
        print(example,lab)
#         coord.request_stop()
#         coord.join(threads)


[[[ 95 124  68]
  [ 91 120  62]
  [ 89 120  63]
  ...
  [ 81 120  57]
  [ 98 133  67]
  [ 80 118  59]]

 [[ 82 117  61]
  [ 90 121  64]
  [ 96 126  72]
  ...
  [ 84 124  62]
  [ 82 124  58]
  [ 76 122  60]]

 [[ 82 117  63]
  [ 87 120  65]
  [ 87 117  65]
  ...
  [ 75 115  55]
  [ 54  98  35]
  [ 68 114  52]]

 ...

 [[ 35  75   2]
  [ 63 104  44]
  [ 91 144  66]
  ...
  [129 156  59]
  [ 58  98  25]
  [ 41  82  14]]

 [[ 73 103   5]
  [117 136  57]
  [160 189 107]
  ...
  [ 60 109  30]
  [ 57 110  38]
  [ 56  92  31]]

 [[113 145  48]
  [ 93 118  17]
  [129 166  73]
  ...
  [191 229 144]
  [ 38  84  20]
  [ 74 110  40]]] 0
[[[ 9 10  5]
  [ 9  9  7]
  [ 3  3  1]
  ...
  [ 1 23  2]
  [21 40 20]
  [14 27 17]]

 [[ 6  6  6]
  [ 5  5  5]
  [32 32 34]
  ...
  [38 52 35]
  [10 25  6]
  [15 25 14]]

 [[11 11  9]
  [ 8  8  6]
  [ 7  7  7]
  ...
  [ 3 20  2]
  [ 7 32  0]
  [35 61 26]]

 ...

 [[56 70  8]
  [73 89 27]
  [47 63  1]
  ...
  [66 86 25]
  [64 81 26]
  [49 63 10]]

 [[53 75 26]
  [28

[[[48 60 24]
  [48 60 24]
  [47 59 23]
  ...
  [39 47 32]
  [37 45 30]
  [38 46 31]]

 [[48 60 24]
  [48 60 24]
  [48 60 24]
  ...
  [36 44 29]
  [34 42 27]
  [33 41 26]]

 [[49 61 25]
  [49 61 25]
  [48 60 24]
  ...
  [33 41 28]
  [32 40 27]
  [30 38 25]]

 ...

 [[16 19 12]
  [15 18 11]
  [13 16  9]
  ...
  [36 15 30]
  [19  7 17]
  [10  6  7]]

 [[16 19 12]
  [15 18 11]
  [14 17 10]
  ...
  [61 28 57]
  [43 21 44]
  [ 6  4  5]]

 [[15 18 11]
  [14 17 10]
  [13 16  9]
  ...
  [89 38 81]
  [77 37 74]
  [27 14 23]]] 3
[[[14 10  9]
  [ 7  5  6]
  [ 4  4  4]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 [[ 8  6  7]
  [ 4  4  4]
  [ 2  2  4]
  ...
  [ 5  3  4]
  [ 4  2  3]
  [ 5  3  4]]

 [[ 6  4  5]
  [ 3  3  5]
  [ 2  3  5]
  ...
  [ 5  4  2]
  [ 7  6  4]
  [ 6  5  3]]

 ...

 [[ 5  5  5]
  [ 5  5  5]
  [ 5  5  5]
  ...
  [ 2  2  2]
  [ 2  2  2]
  [ 3  3  3]]

 [[ 4  4  4]
  [ 5  5  5]
  [ 6  6  6]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 [[ 4  4  4]
  [ 5  5  5]
  [ 6  6  6]
 

[[[218 196 183]
  [219 207 191]
  [225 212 204]
  ...
  [220 209 205]
  [220 209 205]
  [217 206 200]]

 [[184 156 152]
  [193 166 157]
  [221 194 187]
  ...
  [203 184 180]
  [212 193 186]
  [210 191 177]]

 [[139 114 120]
  [163 133 135]
  [156 124 125]
  ...
  [205 179 178]
  [205 177 173]
  [203 174 166]]

 ...

 [[ 70  96  57]
  [ 78 109  78]
  [ 84 119  79]
  ...
  [104 130  69]
  [108 139  80]
  [ 84 112  61]]

 [[103 128  89]
  [ 71 108  57]
  [ 92 130  71]
  ...
  [101 128  73]
  [ 78 111  58]
  [ 43  82  27]]

 [[102 123  80]
  [ 64  97  50]
  [ 58  89  47]
  ...
  [ 95 137  71]
  [ 69 113  54]
  [ 71 117  55]]] 4
[[[157 180 211]
  [157 184 211]
  [159 187 211]
  ...
  [190 206 221]
  [189 205 220]
  [191 207 222]]

 [[163 189 216]
  [167 191 217]
  [164 190 217]
  ...
  [181 202 219]
  [183 204 221]
  [188 209 226]]

 [[175 193 217]
  [179 197 219]
  [167 191 217]
  ...
  [169 196 217]
  [169 196 217]
  [170 197 218]]

 ...

 [[180 187 205]
  [184 193 208]
  [188 197 212]
  