In [4]:
import tensorflow as tf
import os
from PIL import Image

#读取TFRecord文件
filename_queue = tf.train.string_input_producer(['fenlei_train.tfrecords'])  #生成一个queue队列
reader = tf.TFRecordReader()
_,serialized_example = reader.read(filename_queue) #返回文件名和文件

    #解析label和image信息，这个名字需要与生成TFRecord的时候一致
features = tf.parse_single_example(serialized_example,
                                   features={
                                       'label':tf.FixedLenFeature([],tf.int64),
                                       'img_raw':tf.FixedLenFeature([],tf.string)
                                        }) #将image数据个label取出来

img = tf.decode_raw(features['img_raw'],tf.uint8)
img = tf.reshape(img,[64,64,3]) #reshape为64*64的3通道照片
label = tf.cast(features['label'],tf.int32) #tf.cast就是进行数据转换为int32，在数据流中抛出label张量



#把读取到的数据进行保存
cwd = os.getcwd()#获取当前的路径
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord)
    for i in range(40):  #有多少图片就设置为多大
        example,l = sess.run([img,label]) #取出image和label
        img = Image.fromarray(example,'RGB') #image就是之前的
        img.save(cwd+str(i)+'_''label_'+str(l)+'.jpg')#存下图片
        print(example,l)
    coord.request_stop()
    coord.join(threads)
    


[[[11 11 11]
  [ 9  9  9]
  [12 12 12]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 [[ 9 11 10]
  [ 9 11 10]
  [ 9 11 10]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 [[ 9 10 12]
  [ 9 10 12]
  [ 9 10 12]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 ...

 [[ 3  3  3]
  [ 4  4  4]
  [ 5  5  5]
  ...
  [ 8  8  8]
  [ 8  8  8]
  [ 7  7  7]]

 [[ 3  3  3]
  [ 4  4  4]
  [ 5  5  5]
  ...
  [ 9  9  9]
  [ 8  8  8]
  [ 7  7  7]]

 [[ 3  3  3]
  [ 4  4  4]
  [ 5  5  5]
  ...
  [ 7  7  7]
  [ 7  7  7]
  [ 7  7  7]]] 0
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.CancelledError'>, Enqueue operation was cancelled
	 [[Node: input_producer_1/input_producer_1_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](input_producer_1, input_producer_1/Const, ^input_producer_1/Assert/Assert)]]


TypeError: Fetch argument <PIL.Image.Image image mode=RGB size=64x64 at 0x7FCD1F6F7E10> has invalid type <class 'PIL.Image.Image'>, must be a string or Tensor. (Can not convert a Image into a Tensor or Operation.)

In [7]:
import tensorflow as tf
import os
from PIL import Image

#定义读取TFRecord的数据函数
def read_and_decode(filename):
    filename_queue = tf.train.string_input_producer([filename])  #生成一个queue队列
    reader = tf.TFRecordReader()
    _,serialized_example = reader.read(filename_queue) #返回文件名和文件

        #解析label和image信息，这个名字需要与生成TFRecord的时候一致
    features = tf.parse_single_example(serialized_example,
                                       features={
                                           'label':tf.FixedLenFeature([],tf.int64),
                                           'img_raw':tf.FixedLenFeature([],tf.string)
                                            }) #将image数据个label取出来
    img = tf.decode_raw(features['img_raw'],tf.uint8)
    img = tf.reshape(img,[64,64,3]) #reshape为64*64的3通道照片
    label = tf.cast(features['label'],tf.int32) #tf.cast就是进行数据转换为int32，在数据流中抛出label张量
    return img,label


#保存以及显示图片
cwd = os.getcwd() #获取当前的运行路径
init = tf.global_variables_initializer()
batch = read_and_decode('fenlei_train.tfrecords')

with tf.Session() as sess:
    sess.run(init)
    coord = tf.train.Coordinator()
    threads =tf.train.start_queue_runners(coord=coord)

    for i in range(40):
        example, lab = sess.run(batch)
        img = Image.fromarray(example,'RGB')
        img.save(cwd+'/'+str(i)+'_label_'+str(lab)+'.jpg')
        print(example,lab)
        coord.request_stop()
        coord.join(threads)


[[[11 11 11]
  [ 9  9  9]
  [12 12 12]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 [[ 9 11 10]
  [ 9 11 10]
  [ 9 11 10]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 [[ 9 10 12]
  [ 9 10 12]
  [ 9 10 12]
  ...
  [ 3  3  3]
  [ 3  3  3]
  [ 3  3  3]]

 ...

 [[ 3  3  3]
  [ 4  4  4]
  [ 5  5  5]
  ...
  [ 8  8  8]
  [ 8  8  8]
  [ 7  7  7]]

 [[ 3  3  3]
  [ 4  4  4]
  [ 5  5  5]
  ...
  [ 9  9  9]
  [ 8  8  8]
  [ 7  7  7]]

 [[ 3  3  3]
  [ 4  4  4]
  [ 5  5  5]
  ...
  [ 7  7  7]
  [ 7  7  7]
  [ 7  7  7]]] 0
[[[17 22 16]
  [12 11  7]
  [20 26 16]
  ...
  [29 36 29]
  [24 32 17]
  [73 43 33]]

 [[29 35 25]
  [45 47 36]
  [45 52 34]
  ...
  [27 37 29]
  [24 36 26]
  [26 38 24]]

 [[45 54 37]
  [49 55 43]
  [46 53 37]
  ...
  [26 42 32]
  [30 37 30]
  [25 32 24]]

 ...

 [[35 39 14]
  [36 48 28]
  [31 44 24]
  ...
  [83 95 93]
  [81 96 93]
  [65 77 67]]

 [[48 52 27]
  [40 52 32]
  [31 43 23]
  ...
  [77 92 89]
  [81 97 94]
  [54 67 58]]

 [[52 60 39]
  [45 57 37]
  [33 43 19]
 