In [1]:
import numpy as np
a = np.arange(10)**3   #这就是输出10个数字由0开始， **3  这里是代表每个元素的三次方
print(a)      #这出来的就是一个一维的array

[  0   1   8  27  64 125 216 343 512 729]


In [2]:
print(a[2])   #输出下标为2的元素     注意：下标是从0开始计算的

8


In [3]:
print(a[2:5])  #输出下标是2- 4 的元素。  注意：这里一定要很注意跟matlab是不同的。
               #因为 ： 后面的这个数是 False 就像arange函数里面的参数，实际上是到它的前一个数而已
               #注意注意⭐⭐：numpy中startpoint=true，但是endpoint=false  就是说endpoint上的那个数值是不取的，只取到它的前一个数

[ 8 27 64]


In [9]:
a[:6:2] = -1000   #相当于 [0:6:2]    前6个元素，让每个处于偶数位置的数置为-1000   即处于 0 2 4 的位置上的数为-1000  
print(a)

[-1000     1 -1000    27 -1000   125   216   343   512   729]


In [12]:
print(a[ : :-1])

[  729   512   343   216   125 -1000    27 -1000     1 -1000]
