In [3]:
#这个就是检查自己所安装的numpy库的版本
import numpy as np         #第一步就是导入numpy，这是使用numpy的首选必要步骤
print(np.version.version)

1.15.1


In [5]:
print(np.array([1,2,3,4]))  #这个是使用numpy以list为参数产生一维数组

[1 2 3 4]


In [21]:
print(np.array((1.2,2,3,4)))  #这个是使用numpy以tuple为  参数  产生一维数组,产生两个小数位。

[1.2 2.  3.  4. ]


In [12]:
print(type(np.array(1.2)))

<class 'numpy.ndarray'>


In [22]:
print(np.array([[1,2],[3,4]]))  #这个是以list为  元素  产生二维数组

[[1 2]
 [3 4]]


In [24]:
print(np.array([(1,2),(3,4)])) #这个就是以tuple为   元素  产生二位数组

[[1 2]
 [3 4]]


In [39]:
#生成数组的时候还能够指定数据类型，int32 int16 float64
print(np.array((1,2),dtype=np.int32))

[1 2]


In [40]:
print(np.arange(15))     #从0开始生成15个数值
print(np.arange(15.0))   #生成的每个数，都是带有一位小数位的。
print(np.arange(3,9))    #这个就是指定起始的数，要注意的是，最后一位不是到9，是到8.   就是到n-1
print(np.arange(3,9,2))  #这就是指定了起始的数字，间隔为2.以及到9之前的数
print(np.arange(0,1,0.1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
[3 4 5 6 7 8]
[3 5 7]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [32]:
print(type(np.arange(15)))

<class 'numpy.ndarray'>


In [33]:
print(np.arange(15).reshape(3,5))       #把生成的15个数，，重组成一个  3*5  的矩阵

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
