In [2]:
#这个就是检查自己所安装的numpy库的版本
import numpy as np         #第一步就是导入numpy，这是使用numpy的首选必要步骤
print(np.version.version)

1.14.3


In [5]:
print(np.array([1,2,3,4]))  #这个是使用numpy以list为参数产生一维数组

[1 2 3 4]


In [21]:
print(np.array((1.2,2,3,4)))  #这个是使用numpy以tuple为  参数  产生一维数组,产生两个小数位。

[1.2 2.  3.  4. ]


In [12]:
print(type(np.array(1.2)))

<class 'numpy.ndarray'>


In [22]:
print(np.array([[1,2],[3,4]]))  #这个是以list为  元素  产生二维数组

[[1 2]
 [3 4]]


In [24]:
print(np.array([(1,2),(3,4)])) #这个就是以tuple为   元素  产生二位数组

[[1 2]
 [3 4]]


In [39]:
#生成数组的时候还能够指定数据类型，int32 int16 float64
print(np.array((1,2),dtype=np.int32))

[1 2]


In [40]:
print(np.arange(15))     #从0开始生成15个数值，       返回的对象是array，并不是一个list
print(np.arange(15.0))   #生成的每个数，都是带有一位小数位的。
print(np.arange(3,9))    #这个就是指定起始的数，要注意的是，最后一位不是到9，是到8.   就是到n-1
print(np.arange(3,9,2))  #这就是指定了起始的数字，间隔为2.以及到9之前的数
print(np.arange(0,1,0.1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
[3 4 5 6 7 8]
[3 5 7]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [32]:
print(type(np.arange(15)))

<class 'numpy.ndarray'>


In [33]:
print(np.arange(15).reshape(3,5))       #把生成的15个数，，重组成一个  3*5  的矩阵

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [42]:
print(type(np.arange(15).reshape(3,5)))

<class 'numpy.ndarray'>


In [50]:
#linsapce函数()的应用
#np.linspace(start,stop,num=,endpoint=,retstep=,dtype=)   分别对应采样起始点，终结点，采样点的个数，是否作为终结点，如果为true返回sample以及step，最后的是类型
print(np.linspace(1,3,9))      #这个就是从  1到3中产生  9个间隔均匀的数
print(np.linspace(1,10,10))    #这个就是从  1到10   当中产生10个数，这10个数的间隔都是相等的
print(np.linspace(2.0,3.0,num=5))
print(np.linspace(2.0,3.0,num=5,retstep=True))
print(np.linspace(2.0,3.0,num=5,endpoint=False))   #从2到3之间产生5个间隔相等的数，最后一个数字不等于3  

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.  ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[2.   2.25 2.5  2.75 3.  ]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)
[2.  2.2 2.4 2.6 2.8]


In [56]:
#使用numpy.zeros,numpy.ones,numpy.eye等方法构造特定的矩阵
print(np.zeros((3,4)))  #零矩阵
print('\n')
print(np.ones((3,4)))   # 1 矩阵
print('\n')
print(np.eye((3)))      # 单位矩阵

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [60]:
print(np.zeros((2,2,2)))   #创建的一个三维数组
a=np.zeros((2,2,2))
print(a.ndim)  #数组的维数
print(a.shape) #数组中每一维的大小
print(a.size)  #数组中的元素个数
print(a.dtype) #数组中的元素类型
print(a.itemsize) #数组中的每个元素的字节数

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
3
(2, 2, 2)
8
float64
8


In [63]:
#数组中的 索引，切片，赋值     这里的操作是跟matlab中的所有操作时相同的。
a=np.array([[2,3,4],[5,6,7]])
print(a)    #把array对象a输出

print(a[1,2])   #下标是从0开始的，所以这里就是输出 7

print(a[1,:])   #这里就是把第二个元素中的  所有元素所有行所有列全部输出

print(a[1,1:2]) #输出第二个元素里面的  第一行第二列所在的元素 
                #注意注意⭐⭐：numpy中startpoint=true，但是endpoint=false  就是说endpoint上的那个数值是不取的，只取到它的前一个数

a[1,:]=[8,9,10] #进行赋值
print(a)

[[2 3 4]
 [5 6 7]]
7
[5 6 7]
[6]
[[ 2  3  4]
 [ 8  9 10]]


In [71]:
#在numpy中的循环跟在python中的循环是一样的用法    要记住python的语法
for x in np.linspace(1,10,5):
    print(x)

1.0
3.25
5.5
7.75
10.0


In [75]:
#基本的数组运算
a=np.ones((2,2))
b=np.eye(2)
print(a)
print(b)

print(a>2) #逻辑运算

print(a+b) #加
print(a-b) #减

print(b*2) #乘

print((a*2)*(b*2)) 

print(b/(a*2)) #除

print((a*2)**4) #乘方

print(a.sum())  #对所有的元素进行求和

print(a.sum(axis=0))  #计算每一列的和

print(a.min())   #求出全部元素中的最小值

print(a.max())  #求出全部元素中的最大值

[[1. 1.]
 [1. 1.]]
[[1. 0.]
 [0. 1.]]
[[False False]
 [False False]]
[[2. 1.]
 [1. 2.]]
[[0. 1.]
 [1. 0.]]
[[2. 0.]
 [0. 2.]]
[[4. 0.]
 [0. 4.]]
[[0.5 0. ]
 [0.  0.5]]
[[16. 16.]
 [16. 16.]]
4.0
[2. 2.]
1.0
1.0


In [79]:
print(np.sin(a))  

print(np.max(a))

print(np.floor(a))  #地板函数，应该就是向下取整函数
c=np.array([-1.7,-1.5,-0.2,0.2,1.5,1.7,2.0])
print(np.floor(c))

print(np.exp(a))

print(np.dot(a,a))  #矩阵乘法

[[0.84147098 0.84147098]
 [0.84147098 0.84147098]]
1.0
[[1. 1.]
 [1. 1.]]
[-2. -2. -1.  0.  1.  1.  2.]
[[2.71828183 2.71828183]
 [2.71828183 2.71828183]]
[[2. 2.]
 [2. 2.]]


In [84]:
#数组的合并运算
a=np.ones((2,2))
b=np.eye(2)
print(np.vstack((a,b)))  #竖向合并

print(np.hstack((a,b)))  #横向合并

[[1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 1.]]
[[1. 1. 1. 0.]
 [1. 1. 0. 1.]]


In [91]:
#浅拷贝与深拷贝 的问题
c=np.hstack((a,b))
print(c)

a[1,1]=5
b[1,1]=5
print(a)
print(b)

print(c)  #从这里可以看出，即使矩阵a，b已经改变了， 但是c并没有受到影响， 没有发生改变

#=========================================================================================================================================
a=np.ones((2,2))   #这里就是创建一个二阶的 1矩阵
b=a                #这不会创建新的对象
b is a             #a和b只是同一个对象的两个名字  所以在这里进行逻辑判断的时候就是对的  true


c=a.copy()         #在这里就是创建了新的数组和新的数据 
c is a             #所以就不是完全一样的了         运行就是false

c == a             #这里可以进行判断数据是否相同 ，那肯定是 true的啊

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1.]
 [1. 5.]]
[[1. 1.]
 [1. 5.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[ True,  True],
       [ True,  True]])

In [94]:
#矩阵的基本运算
a=np.array([[1,0],[2,3]])
print(a)

print(a.transpose())    #这里就是矩阵的转置

print('\n')

print(np.trace(a))      #这里就是计算 矩阵的迹    就是正对角线之和

[[1 0]
 [2 3]]
[[1 2]
 [0 3]]


4


In [95]:
#numpy中的numpy.linalg模块有很多关于矩阵运算的方法

import numpy.linalg as nplg   #第一步还是引入这个模块啦
print(nplg.eig(a))          #这里就是计算特征值与特征向量

(array([3., 1.]), array([[ 0.        ,  0.70710678],
       [ 1.        , -0.70710678]]))


In [7]:
#numpy创建随机数组
print(np.random.rand(10,10))       #创建一个10行10列的随机数组，每一个元素之间的数值都在0-1
print('\n')

print(np.random.uniform(0,100))    #创建一个制定范围内的随机数  本例子是0-100print('\n')
print('\n')

print(np.random.randint(0,100))    #这是创建一个0-100范围内的一个整数

[[0.6656865  0.31265517 0.44611288 0.73412534 0.01655963 0.13220714
  0.77129818 0.92109254 0.69907597 0.5936764 ]
 [0.22909461 0.1485645  0.7788661  0.43473049 0.07296655 0.50915892
  0.89591812 0.41734344 0.54545941 0.95515345]
 [0.45611037 0.83805763 0.8831515  0.32308728 0.13464086 0.49654278
  0.77677816 0.64964005 0.73796127 0.58009971]
 [0.68007784 0.62021544 0.98728131 0.23947884 0.9344107  0.57190442
  0.64990633 0.61934101 0.18842414 0.5509758 ]
 [0.61085107 0.24047511 0.46787744 0.06619384 0.662231   0.61997704
  0.05668059 0.13125375 0.44098742 0.1687499 ]
 [0.08776277 0.06520556 0.99134478 0.54768204 0.23261125 0.09296178
  0.21467867 0.90006129 0.35618149 0.77174666]
 [0.89571609 0.56106713 0.96284575 0.32782484 0.78769034 0.2990426
  0.83186967 0.53584158 0.81595728 0.61055027]
 [0.1425515  0.13899925 0.60514613 0.74751853 0.38996834 0.6871649
  0.06245533 0.83890472 0.23196373 0.82205268]
 [0.09539189 0.66658048 0.20173626 0.24044504 0.42653445 0.86287221
  0.19504856 0

In [12]:
#正态分布
f=np.random.normal(1.75,0.1,(4,5))
print(f)   #这就是给定了 平均值，标准差， 维度 的正态分布
print('\n')
x=f[1:3,2:4]  #注意注意⭐⭐：numpy中startpoint=true，但是endpoint=false  就是说endpoint上的那个数值是不取的，只取到它的前一个数
              #第二种说法就是：在python中属于 范围类的集合型数制是包含首而包含尾的。举个例子 给定一个范围（3，10）就是包含3，不包含10的
print(x)

[[1.59180901 1.91299835 1.7394277  1.7354939  1.86935566]
 [1.77084983 1.58347063 1.67313788 1.71311609 1.53690042]
 [1.7417051  1.7400402  1.90683649 1.60742252 1.78012505]
 [1.79124207 1.65188341 1.91870387 1.87343671 1.70262191]]


[[1.67313788 1.71311609]
 [1.90683649 1.60742252]]
